# Generated by Django 2.0.7 on 2018-07-30 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 30, 17, 16, 25, 275591, tzinfo=utc)),
        ),
    ]
