# Generated by Django 2.0.7 on 2018-07-30 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180730_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 30, 17, 30, 31, 150413, tzinfo=utc)),
        ),
    ]
