# Generated by Django 2.0.7 on 2018-08-01 01:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180730_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 1, 24, 3, 42231, tzinfo=utc)),
        ),
    ]
