# Generated by Django 2.0.7 on 2018-08-03 03:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20180731_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 3, 13, 40, 683692, tzinfo=utc)),
        ),
    ]
