# Generated by Django 2.0.7 on 2018-08-05 23:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20180802_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 5, 23, 16, 17, 210027, tzinfo=utc)),
        ),
    ]
