# Generated by Django 2.0.7 on 2018-08-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('site', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
            ],
        ),
    ]
