# Generated by Django 2.0.7 on 2018-07-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='author',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='title',
            field=models.CharField(default='text', max_length=30),
            preserve_default=False,
        ),
    ]
