# Generated by Django 2.0.7 on 2018-08-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0002_auto_20180730_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='github',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mail',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
