# Generated by Django 2.0.7 on 2018-08-01 03:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 8, 1, 3, 27, 20, 529129, tzinfo=utc))),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
