# Generated by Django 2.0.7 on 2018-08-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('site', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('body', models.TextField()),
            ],
        ),
    ]
